spring.application.name=OrderAndInventoryManagement

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/orderandinventory
spring.datasource.username=postgres
spring.datasource.password=123

server.port=8082

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

